import 'dart:typed_data';
import 'package:uuid/uuid.dart';

/// ── Message Role ───────────────────────────────────────────────────────────
/// Identifies who authored a message in the chat.
enum MessageRole {
  /// Message sent by the user.
  user,

  /// Response generated by the AI assistant.
  assistant,

  /// System-level message (welcome, errors, etc.).
  system,
}

/// ── Chat Message Model ─────────────────────────────────────────────────────
/// Immutable data class representing a single message in the conversation.
/// Uses a UUID for unique identification and stores metadata like timestamps.
class ChatMessage {
  /// Unique identifier for this message.
  final String id;

  /// Who sent this message.
  final MessageRole role;

  /// The text content of the message.
  final String content;

  /// When the message was created.
  final DateTime timestamp;

  /// Whether this message is currently being streamed/generated.
  final bool isStreaming;

  /// Whether this message represents an error state.
  final bool isError;

  /// Optional image data attached to this message (for Vision).
  final Uint8List? imageData;

  ChatMessage({
    String? id,
    required this.role,
    required this.content,
    DateTime? timestamp,
    this.isStreaming = false,
    this.isError = false,
    this.imageData,
  })  : id = id ?? const Uuid().v4(),
        timestamp = timestamp ?? DateTime.now();

  /// Creates a copy of the message with optional updated fields.
  ChatMessage copyWith({
    String? content,
    bool? isStreaming,
    bool? isError,
    Uint8List? imageData,
  }) {
    return ChatMessage(
      id: id,
      role: role,
      content: content ?? this.content,
      timestamp: timestamp,
      isStreaming: isStreaming ?? this.isStreaming,
      isError: isError ?? this.isError,
      imageData: imageData ?? this.imageData,
    );
  }

  /// Creates a user message with the given [content] and optional [imageData].
  factory ChatMessage.user(String content, {Uint8List? imageData}) {
    return ChatMessage(
      role: MessageRole.user, 
      content: content,
      imageData: imageData,
    );
  }

  /// Creates an assistant message with the given [content].
  factory ChatMessage.assistant(String content, {bool isStreaming = false, bool isError = false}) {
    return ChatMessage(
      role: MessageRole.assistant,
      content: content,
      isStreaming: isStreaming,
      isError: isError,
    );
  }

  /// Creates a system message with the given [content].
  factory ChatMessage.system(String content) {
    return ChatMessage(role: MessageRole.system, content: content);
  }

  /// Returns true if this is a user-sent message.
  bool get isUser => role == MessageRole.user;

  /// Returns true if this is an AI-generated response.
  bool get isAssistant => role == MessageRole.assistant;

  /// Returns a formatted time string (HH:MM).
  String get formattedTime {
    final hour = timestamp.hour.toString().padLeft(2, '0');
    final minute = timestamp.minute.toString().padLeft(2, '0');
    return '$hour:$minute';
  }

  @override
  String toString() => 'ChatMessage($role: "${content.substring(0, content.length.clamp(0, 50))}...")';
}
