; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BE275555-F8E5-47ED-A637-DE76FF707A8C}
AppName=FlowDesk
AppVersion=1.0.1
;AppVerName=FlowDesk 1.0.1
AppPublisher=My Company, Inc.
AppPublisherURL=https://www.example.com/
AppSupportURL=https://www.example.com/
AppUpdatesURL=https://www.example.com/
DefaultDirName={autopf}\FlowDesk
UninstallDisplayIcon={app}\invisible_ai_assistant.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\avipa\Downloads
OutputBaseFilename=flowdesk
SetupIconFile=C:\Users\avipa\invisible_ai_assistant\assets\app_icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\auto_updater_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\bitsdojo_window_windows_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\dartjni.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\flutter_secure_storage_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\hotkey_manager_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.exp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\native_assets.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\record_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\tray_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\window_protection_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\WinSparkle.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\FlowDesk"; Filename: "{app}\invisible_ai_assistant.exe"
Name: "{autodesktop}\FlowDesk"; Filename: "{app}\invisible_ai_assistant.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\invisible_ai_assistant.exe"; Description: "{cm:LaunchProgram,FlowDesk}"; Flags: nowait postinstall skipifsilent

