; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{44CF766A-5D38-439A-8442-D94BF660E581}
AppName=Invisible_meet_ai
AppVersion=1.0.0
;AppVerName=Invisible_meet_ai 1.0.0
AppPublisher=My Company, Inc.
AppPublisherURL=https://www.example.com/
AppSupportURL=https://www.example.com/
AppUpdatesURL=https://www.example.com/
DefaultDirName={autopf}\Invisible_meet_ai
UninstallDisplayIcon={app}\invisible_ai_assistant.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\avipa\Downloads
OutputBaseFilename=invisible_meet_ai
SetupIconFile=C:\Users\avipa\invisible_ai_assistant\assets\app_icon.ico
SolidCompression=yes
WizardStyle=modern dark windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\auto_updater_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\bitsdojo_window_windows_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\dartjni.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\flutter_secure_storage_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\hotkey_manager_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.exp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\invisible_ai_assistant.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\native_assets.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\record_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\tray_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\window_protection_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\WinSparkle.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\avipa\invisible_ai_assistant\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\Invisible_meet_ai"; Filename: "{app}\invisible_ai_assistant.exe"
Name: "{autodesktop}\Invisible_meet_ai"; Filename: "{app}\invisible_ai_assistant.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\invisible_ai_assistant.exe"; Description: "{cm:LaunchProgram,Invisible_meet_ai}"; Flags: nowait postinstall skipifsilent

